import React from 'react';
import {Calendar2, CardPos, Note1, Briefcase} from 'iconsax-react-native';

const CHAT_CONST = {
  ChatTabBarData: [
    {
      id: 1,
      title: 'All Reviews',
      //icon: true,
      activeColor: '#5948AA',
    },
    {
      id: 2,
      title: 'Eyelashes',
      activeColor: '#5948AA',
    },
  ],
  emptyList: [],
  chatListData: [
    {
      id: 1,
      image: null,
      name: 'Alice Berton',
      desc: 'Hi there, how can i help you?',
      time: '9:39 PM',
      isVerify: true,
      isOnline: true,
      unread: 4,
      responseTime: 'under 1h',
    },
    {
      id: 2,
      image: null,
      name: 'Kristin Watson',
      desc: 'Hi Alice',
      time: '8:30 PM',
      isVerify: true,
      isOnline: false,
      unread: null,
      responseTime: 'under 1h',
    },
    {
      id: 3,
      image: null,
      name: 'Alex Flores',
      desc: 'Hi there, how can i help you?',
      time: '8:00 PM',
      isVerify: true,
      isOnline: true,
      unread: 1,
      responseTime: 'under 1h',
    },
    {
      id: 4,
      image: null,
      name: 'Albert Flores',
      desc: 'Hi there, how can i help you? I have a question about',
      time: '7:00 PM',
      isVerify: false,
      isOnline: false,
      unread: 3,
      responseTime: 'under 1h',
    },
    {
      id: 5,
      image: null,
      name: 'Albert Flores',
      desc: 'Hi there, how can i help you? I have a question about',
      time: '7:00 PM',
      isVerify: false,
      isOnline: false,
      unread: 3,
      responseTime: 'under 1h',
    },
    {
      id: 6,
      image: null,
      name: 'Albert Flores',
      desc: 'Hi there, how can i help you? I have a question about',
      time: '7:00 PM',
      isVerify: false,
      isOnline: false,
      unread: 3,
      responseTime: 'under 1h',
    },
    {
      id: 7,
      image: null,
      name: 'Albert Flores',
      desc: 'Hi there, how can i help you? I have a question about',
      time: '7:00 PM',
      isVerify: false,
      isOnline: false,
      unread: 3,
      responseTime: 'under 1h',
    },
    {
      id: 8,
      image: null,
      name: 'Albert Flores',
      desc: 'Hi there, how can i help you? I have a question about',
      time: '7:00 PM',
      isVerify: false,
      isOnline: false,
      unread: 3,
      responseTime: 'under 1h',
    },
    {
      id: 9,
      image: null,
      name: 'Albert Flores',
      desc: 'Hi there, how can i help you? I have a question about',
      time: '7:00 PM',
      isVerify: false,
      isOnline: false,
      unread: 3,
      responseTime: 'under 1h',
    },
    {
      id: 10,
      image: null,
      name: 'Albert Flores',
      desc: 'Hi there, how can i help you? I have a question about',
      time: '7:00 PM',
      isVerify: false,
      isOnline: false,
      unread: 3,
      responseTime: 'under 1h',
    },
  ],
  notificationListData1: [
    {
      id: 1,
      image: null,
      icon: <Calendar2 size={22} color="#717171" />,
      title: 'Eyelash',
      desc: 'You can pay 20$ for one-month...',
      time: '30m',
      hasAction: true,
    },
    {
      id: 2,
      image: null,
      icon: null,
      title: 'Alice Brain',
      desc: 'You can preview two exclusive stories for free this month.',
      time: '2h',
      hasAction: false,
    },
  ],
  notificationListData2: [
    {
      id: 1,
      image: null,
      icon: <CardPos size={22} color="#717171" />,
      title: 'Eyelash',
      desc: 'You can pay 20$ for one-month...',
      time: '30m',
      hasAction: true,
    },
    {
      id: 2,
      image: null,
      icon: null,
      title: 'Alice Brain',
      desc: 'You can preview two exclusive stories for free this month.',
      time: '2h',
      hasAction: false,
    },
    {
      id: 3,
      image: null,
      icon: <Note1 size={22} color="#717171" />,
      title: 'Eyelash',
      desc: 'You can pay 20$ for one-month...',
      time: '30m',
      hasAction: true,
    },
    {
      id: 4,
      image: null,
      icon: <Briefcase size={22} color="#717171" />,
      title: 'Alice Brain',
      desc: 'You can preview two exclusive stories for free this month.',
      time: '2h',
      hasAction: true,
    },
  ],
  messageList: [
    {
      id: 1,
      isMe: true,
      type: 'text', //text, voice, image, video
      content: 'hi alice , how you doin?',
      isReply: false,
      replyBy: '',
      replyType: '',
      replyContent: '',
      time: '5:10 PM',
      size: '',
      status: '',
    },
    {
      id: 2,
      isMe: false,
      type: 'text', //text, voice, image, video
      content: 'hi there, how can i help you?',
      isReply: false,
      replyBy: '',
      replyType: '',
      replyContent: '',
      time: '5:10 PM',
      size: '',
      status: '',
    },
    {
      id: 3,
      isMe: false,
      type: 'text', //text, voice, image, video
      content:
        'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry`s standard dummy text ever since the 1500s.',
      isReply: false,
      replyBy: '',
      replyType: '',
      replyContent: '',
      time: '5:10 PM',
      size: '',
      status: '',
    },
    {
      id: 4,
      isMe: true,
      type: 'text', //text, voice, image, video
      content: 'Thanks',
      isReply: true,
      replyBy: 'You',
      replyType: 'voice',
      replyContent: 'hi there, how can i help you?',
      time: '5:10 PM',
      size: '',
      status: '',
    },
    {
      id: 5,
      isMe: false,
      type: 'text', //text, voice, image, video
      content: 'no problem',
      isReply: false,
      replyBy: '',
      replyType: '',
      replyContent: '',
      time: '5:10 PM',
      size: '',
      status: '',
    },
    {
      id: 6,
      isMe: true,
      type: 'text', //text, voice, image, video
      content: 'Ok',
      isReply: false,
      replyBy: '',
      replyType: '',
      replyContent: '',
      time: '5:10 PM',
      size: '',
      status: '',
    },
    {
      id: 7,
      isMe: false,
      type: 'image', //text, voice, image, video
      content: require('../assets/media/ChatVideoSample.png'),
      isReply: true,
      replyBy: 'You',
      replyType: 'text',
      replyContent: 'no problem',
      time: '5:10 PM',
      size: '',
      status: '',
    },
  ],
  messageActionList: [
    {
      key: 1,
      title: 'Edit Message',
      value: 'Edit Message',
    },
    {
      key: 2,
      title: 'Delete Message',
      value: 'Delete Message',
    },
    {
      key: 3,
      title: 'Unsend Message',
      value: 'Unsend Message',
    },
  ],
  chatActionList: [
    {
      key: 1,
      title: 'Block Contact',
      value: 'Block Contact',
    },
    {
      key: 2,
      title: 'Remove Message',
      value: 'Remove Message',
    },
    {
      key: 3,
      title: 'Pin Conversation',
      value: 'Pin Conversation',
    },
  ],
  chatFAQList: [
    {
      title: 'Question Title 1',
      desc: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry`s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
    },
    {
      title: 'Question Title 2',
      desc: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry`s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
    },
    {
      title: 'Question Title 3',
      desc: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry`s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
    },
  ],
};

export {CHAT_CONST};
